#%RAML 1.0 DataType
type: object
properties:
  Id?:
    type: string
    required: false
  OwnerId?:
    type: string
    required: false
  IsDeleted?:
    type: boolean
    required: false
  Name?:
    type: string
    required: false
  CurrencyIsoCode?:
    type: string
    required: false
  CreatedDate?:
    type: datetime
    required: false
  CreatedById?:
    type: string
    required: false
  LastModifiedDate?:
    type: datetime
    required: false
  LastModifiedById?:
    type: string
    required: false
  SystemModstamp?:
    type: datetime
    required: false
  LastActivityDate?:
    type: date-only
    required: false
  LastViewedDate?:
    type: datetime
    required: false
  LastReferencedDate?:
    type: datetime
    required: false
  Cleansed_Unomy_Company_Name__c?:
    type: string
    required: false
  ID_Status__c?:
    type: string
    required: false
  Is_Active__c?:
    type: boolean
    required: false
  Parent_Account__c?:
    type: string
    required: false
  UUID__c?:
    type: string
    required: false
  Primary_Member__c?:
    type: string
    required: false
  Legacy_Account_Owner__c?:
    type: string
    required: false
  Legacy_Account_Id__c?:
    type: string
    required: false
  External_Billing_Account_Id__c?:
    type: string
    required: false
  Cleansed_Account_Name__c?:
    type: string
    required: false
  Conventional_Name__c?:
    type: string
    required: false
  Lead_Source__c?:
    type: string
    required: false
  Legacy_Account__c?:
    type: string
    required: false
  Number_Of_Lost_Opportunities__c?:
    type: number
    required: false
  Number_Of_Open_Opportunities__c?:
    type: number
    required: false
  Number_Of_Total_Opportunities__c?:
    type: number
    required: false
  Number_Of_Won_Opportunities__c?:
    type: number
    required: false
  Number_of_Full_Time_Employees__c?:
    type: number
    required: false
  Org_Record_Type__c?:
    type: string
    required: false
  Parent_Org__c?:
    type: string
    required: false
  Phone__c?:
    type: number
    required: false
  Region_Name__c?:
    type: string
    required: false
  Ultimate_Parent_Org__c?:
    type: string
    required: false
  AutorabitExtId__c?:
    type: string
    required: false
  Primary_Member_Email__c?:
    type: string
    required: false
  Primary_Member_Name__c?:
    type: string
    required: false
  CI_Company__c?:
    type: string
    required: false
  Unomy_Company_Name_Formula__c?:
    type: string
    required: false
  Managed_By__c?:
    type: string
    required: false
  fieldsToNull?:
    type: string []
    required: false

example:
  Id:  sald123a
  OwnerId?: opk2323
  IsDeleted?: true
  Name?: james
  CurrencyIsoCode?: ls23
  CreatedDate?: "2019-06-18T16:55:46.678-07:00"
  CreatedById?: kfkjas3 
  LastModifiedDate: "2019-06-18T16:55:46.678-07:00"
  LastModifiedById?: dfnalk43
  SystemModstamp?: "2019-06-18T16:55:46.678-07:00"
  LastActivityDate?: "2019-06-18"
  LastViewedDate?: "2019-06-18T16:55:46.678-07:00"
  LastReferencedDate?: "2019-06-18T16:55:46.678-07:00"
  Cleansed_Unomy_Company_Name__c?: kore
  ID_Status__c?: pending
  Is_Active__c?: true
  Parent_Account__c?: owner
  UUID__c?: adla4-sdfsad-dfads-adfdas
  Primary_Member__c?: fdsafj
  Legacy_Account_Owner__c?: adsfsda
  Legacy_Account_Id__c?: fdfasdf
  External_Billing_Account_Id__c?: adsfdas
  Cleansed_Account_Name__c?: dfweewf
  Conventional_Name__c?: dafdsf
  Lead_Source__c?: adfds
  Legacy_Account__c?: rewrwe
  Number_Of_Lost_Opportunities__c?: 454
  Number_Of_Open_Opportunities__c?: 55
  Number_Of_Total_Opportunities__c?: 43
  Number_Of_Won_Opportunities__c?: 433
  Number_of_Full_Time_Employees__c?: 75
  Org_Record_Type__c?: sdfjsld
  Parent_Org__c?: ljlkjl
  Phone__c?: 12324324324
  Region_Name__c?: nvlkd
  Ultimate_Parent_Org__c?: fldsflk
  AutorabitExtId__c?: fjpmfl
  Primary_Member_Email__c?: flkdsafo
  Primary_Member_Name__c?: nfldsnflk
  CI_Company__c?: lkmlml
  Unomy_Company_Name_Formula__c?: fdskajf
  fieldsToNull?: [adsa,dfdsaf]
