#%RAML 1.0 DataType
description:
type: array
items:
  type: object
  properties:
    Risk_Screen__c: string
    CompositeRSQ_ID__c: string
    BusinessUnitID__c?: string | nil
    ClientProspectID__c: string
    ClientOnboardingID__c: string
    OnboardingPropertyGroupID__c: string
    OnboardingPropertyID__c: string
    StoreID__c: string
    Integer__c?: string | nil
    Decimal__c?: string | nil
    Text__c?: string | nil
    Date__c?: date-only | nil
    ListGroupID__c?: string | nil
    ListDataID__c?: string | nil
    DateLastChanged__c: datetime
    LastChangedByUserID__c?: string | nil

    
    
    
    
    
    
    
    
    
  


      
  



      

      
          
    

      
      
      
        
      
      
  