#%RAML 1.0 DataType
description:
type: array
items:
  type: object
  properties:
    Id: string
    ClientProspectID__c?: string | nil
    ClientOnboardingID__c?: string | nil
    OnboardingStatus__c: string
    OnboardingStageID__c?: string | nil
    ClientEntityID__c?: string | nil
    DateLastChanged__c: datetime

    
    
    
    
    
    
    
    
    
  


      
  



      

      
          
    

      
      
      
        
      
      
  