#%RAML 1.0 DataType

type: object
properties:
  Name: string
  Building_Legal_Name__c: string
  Gross_Desks__c?: number |nil
  Net_Desks__c?: number |nil
  Net_TCV_Unweighted_Formula__c?: number |nil
  Gross_ACV__c?: number | nil
  Net_ACV_Unweighted__c?: number |nil
  Gross_TCV_Formula__c?: number |nil
  Gross_Term_TCV__c: number |nil
  StageName?: string
  Type__c?: string
  Interested_in_Number_of_Desks__c?: number | nil
  OwnerId?: string
  Segment__c?: string | nil
  Building__c?: string
  RecordTypeId?: string | nil
  AccountId?: string
  CreatedDate?: datetime
  Contract_Type__c?: string |nil
  Contract_Pdf__c?: string | nil
  Type__c ?: string
  id?: string