anypoint.platform:
  client_secret: "![]"
  
certificates:
  keystore:
    password: "![]"

rollbar:
  accesstoken: "![]"

sf:
  consumer-key: "![]"
  consumer-secret: "![]"
  password: "![]"
  