anypoint.platform:
  client_secret: "![eMJBxOWObU/s0m00FAUdEP+QhC3IsQUu63tGDvH/a6AJRLnC0bATsQ==]"
  
rollbar:
  accesstoken: "![]"
  
sf:
  consumer-key: "![]"
  consumer-secret: "![]"
  password: "![]"