#%RAML 1.0 Trait
  
headers:
  authorization:
    description: Bearer 
    type: string
responses:
  400:
    description: JWT token is required.
  401:
    description: Bad or expired token. To fix, you should re-authenticate the user.
  403:
    description: The client id validation failed.
  503:
    description: Error communicating with JWKS server.