#%RAML 1.0 DataType
properties:
  contactID?:
    type: string
  accountUUID?:
    type: string | nil
  accountId?:
    type: string
  accountName?:
    type: string
  accountStatus?:
    type: string
  email?:
    type: string
  name?:
    type: string
  uuid?:
    type: string
  phone?:
    type: string
  location?:
    type: string | nil
  locale?:
    type: string
  language?:
    type: string
  roles?:
    type: string | nil
  statusID?:
    type: string
  Id?: string
  FirstName?: string
  LastName?: string
  Title?: string
  Company?: string
  LeadSource?: string
  LeadSource_Sub_Type__c?: string
  Lead_Source_Detail__c?: string
  