#%RAML 1.0 DataType

type: array
items:
  properties:
    Id?: string
    Net_TCV_unweighted__c?: string | nil
    Gross_TCV__c?: string | nil
    TCV_Default_Currency__c?: string | nil
    Net_TCV_Local_Payload__c?: string | nil
    ACV_Gross__c?: string | nil
    ACV_Net__c?: string | nil
    Addon_Gross__c?: string | nil
    tcv_gross_salesrecords_uuids__c?: string | nil
    tcv_net_salesrecords_uuids__c?: string | nil
    tcv_addons_salesrecords_uuids__c?: string | nil
    tcv_discounts_salesrecords_uuids__c?: string | nil
    StageName?: string | nil
    TCV_Updated__c?: string | nil | boolean
    TCV_Date_Time_Updated__c?: string | nil