#%RAML 1.0 DataType

type: array
items:
  properties:
    UUID__c?: string
    Applied_Months__c?: string | nil
    Contract_Kind__c?: string | nil
    Membership_Agreement_Uuid__c?: string | nil
    Price__c?: string | nil
    Product_Uuid__c?: string | nil
    Promotion_Code__c?: string | nil
    Quantity__c?: string | nil
    Inventory_Type__c?: string | nil
    End_Date__c?: date-only
    Start_Date__c?: date-only
    Term_Start_Date__c?: date-only
    Term_End_Date__c?: date-only
    Type__c?: string | nil
    Units_Changed__c?: integer | nil
    Record_Local_Value__c?: string | nil
    CurrencyIsoCode?: string | nil
    Reservation_Uuid__c?: string | nil
    Opportunity__c?: string | nil
    billing_account__r?: object | nil
    inventory__r?: object | nil
    Primary_Reservation__r?: object | nil
    building__r?: object | nil