#%RAML 1.0 DataType
type: object
properties:
  applicationName:
    type: string
    description: Application Name
    example: "wwj-salesforce-sapi"
  applicationVersion:
    type: string
    description: Application Version
    example: "v1"
  environment:
    type: string
    description: Environment
    example: "UAT"
  status:
    type: string
    description: Status of API
    example: "Running"