#%RAML 1.0 NamedExample
apiName: "test api"
version: "v1"
correlationId: "sddsa-121-231231-22ss"
errorDescription: "This is test"
errorCode: "Mule123"
timestamp: "2021-02-28T16:41:41.090Z"
errorType: "UNAUTHORIZED"