#%RAML 1.0 DataType

  type: object
  properties:
    Id?: string
    Name?: string | nil
    Phone?: string | nil
    Primary_Member__c?: string | nil
    Number_of_Full_Time_Employees__c?: string | nil
    Lead_Source__c?: string | nil
    LeadSource_Sub_Type__c?: string | nil
    UUID__c?: string | nil
    ID_Status__c?: string | nil
    Account_Type__c?: string | nil
    Active__c?: string | nil
    Duplicate_status__c?: string | nil