#%RAML 1.0 DataType

  type: object
  properties:
    Id?: string
    Name?: string | nil
    ParentId?: string | nil
    Ultimate_Parent_Org__c?: string | nil
    Primary_Member__c?: string | nil
    UUID__c?: string | nil
    Account_shortCode?: string | nil
    Account_Manager_Name?: string | nil
    currencyISOCode?:  string | nil