#%RAML 1.0 DataType
properties:
  Id?: string
  UUID__c?: string
  Name?: string | nil
  Leasing_Director__c?: string | nil
  Address__c?: string | nil
  Country__c?: string | nil
  City__c?: string | nil
  State__c?: string | nil
  Postal_Code__c?: string | nil
  CurrencyIsoCode?: string | nil
  Building_ID__c?: string | nil
  Legal_Licensor_Name__c?: string | nil
  Email__c?: string | nil
  Market__c?: string | nil
  Contract_Status__c?: string | nil
  Community_Manager__c?: string | nil
  Time_Zone__c?: string | nil
  Territory_Name__c?: string | nil
  Location_No_City__c?: string | nil
  Phone_Number__c?: string | nil