#%RAML 1.0 DataType
properties:
  reservable_uuid?: string | nil
  building_uuid?: string | nil
  price: 
    type: number
    format: double
    required: false
  quantity?: integer | nil
  move_out_date?: string | nil
  reservation_uuid?: string | nil
  membership_agreement_uuid?: string | nil
  company_uuid?: string | nil