#%RAML 1.0 DataType
description:
type: object
properties:
  Medallia_Account_Management__c:
    required: false
    type: number | nil
  Medallia_Building_Operations__c:
    required: false
    type: number | nil
  Medallia_Likelihood_to_Renew__c:
    required: false
    type: number | nil
  Medallia_Move_Out_Survey_Results__c:
    required: false
    type: string | nil
  Medallia_Survey_Response__c:
    required: false
    type: string | nil
  Medallia_Verbatim_Feedback__c:
    required: false
    type: string | nil
  Medallia_Vibe_Energy__c:
    required: false
    type: number | nil
  Medallia_Work_Productivity__c:
    required: false
    type: number | nil
  Contact__c:
    required: true
    type: string 
