#%RAML 1.0 DataType
properties:
      reservable_uuid: 
        type: string | nil
        required: false
      building_uuid: 
        type: string | nil
        required: false
      price: 
        type: number
        format: double
        required: false
      quantity: 
        type: integer | nil | string
        required: false
      start_date: 
        type: date-only | nil
        required: false
      reservation_uuid:
        type: string | nil
        required: false
    