#%RAML 1.0 DataType

type: object
properties:
  Id?: string
  StageName: string
  LeadSource?: string
  LeadSource_Sub_Type__c?: string
  Lead_Source_Detail__c?: string
  Opportunity_Creation_Source__c?: string | nil
  CloseDate?: date-only
  Actual_Start_Date__c?: date-only
  Building__c: string
  Source_Id__c?: string | nil
  Account?: string
  Primary_Member__c?: string
  Interested_in_Number_of_Desks__c?: number | nil
  OwnerId?: string
  Uom__c?: string | nil
  Original_Quantity__c?: number
  Description?: string | nil
  IsRenewalOpportunity__c?: boolean
  CreatedDate?: datetime
  IsClosed?: boolean
  Name?: string
  Primary_Contact__c?: string | nil
  Main_Contact_ID__c?: string
  USF_Quantity__c?: number | nil
  Desired_Term_Length_in_months__c?: number
  Type__c ?: string