#%RAML 1.0 DataType
description: Request body to update contact in salesforce.
type: object
properties:
  Marketing_Consent__c: 
    required: false
    type: boolean | nil
  HasOptedOutOfEmail: 
    required: false
    type: boolean | nil