#%RAML 1.0 DataType

type: object
properties:
  Id?: string
  WhoId?: string
  Status?: string
  Priority?: string
  Subject?: string
  Building__c?: string
  Type?: string
  Description?: string
  OwnerId?: string
  WhatId?: string
  ActivityDate?: date-only
  Lead_Source__c?: string
  ExternalId__c?: string