#%RAML 1.0 DataType

type:
  object
properties:
  start_time:
    type: string
    required: true
  end_time:
    type: string
    required: true
  notes:
    type: string
    required: false
  building_id:
    type: string
    required: true
  booked_by_id:
    type: string
    required: false
  source:
    type: string
    required: false
  lead_source_details:
    type: string
    required: false
  first_name:
    type: string
    required: true
  last_name:
    type: string
    required: true
  phone:
    type: string
    required: false
  email:
    type: string
    required: true
  company_name:
    type: string
    required: true
  contact_uuid:
    type: string
    required: false
  company_size:
    type: string
    required: false
  company_industry:
    type: string
    required: false
  service_resource_id:
      type: string
      required: false
  number_of_desks:
    type: integer
    required: false
  booked_by_contact_id: 
    type: string
    required: false
  booked_by_sales_lead:
    type: boolean
    required: false
  lead_source:
    type: string
    required: false
  locale:
    type: string
    required: false
  country_code:
    type: string
    required: false
  opportunity_id:
    type: string
    required: false
  utm_campaign:
    type: string
    required: false
  utm_content:
    type: string
    required: false
  utm_medium:
    type: string
    required: false
  utm_source:
    type: string
    required: false 
  utm_term:
    type: string
    required: false
  journey_sfid:
    type: string
    required: false 
  tour_format:
    type: string
    required: false  